horses:
  sets: {}
  parts:
    faces:
      collection:
        - tid: 0
    coats:
      collection:
        - tid: 0
          faceType: -1
    manes:
      collection:
        - tid: 0
    tails:
      collection:
        - tid: 0