missions:
- id: 1
  gameMode: 1
  nextMissionId: 0
  mapId: 65
  minLevel: 1
  maxLevel: 0
  preMissionId: 0
  waitingTime: 0
  reward: 0
  closed: true
- id: 2
  gameMode: 1
  nextMissionId: 0
  mapId: 65
  minLevel: 1
  maxLevel: 0
  preMissionId: 0
  waitingTime: 0
  reward: 0
  closed: true
- id: 3
  gameMode: 1
  nextMissionId: 0
  mapId: 67
  minLevel: 1
  maxLevel: 0
  preMissionId: 0
  waitingTime: 0
  reward: 0
  closed: true
- id: 4
  gameMode: 1
  nextMissionId: 0
  mapId: 66
  minLevel: 1
  maxLevel: 0
  preMissionId: 0
  waitingTime: 0
  reward: 0
  closed: true
- id: 5
  gameMode: 1
  nextMissionId: 0
  mapId: 66
  minLevel: 1
  maxLevel: 0
  preMissionId: 0
  waitingTime: 0
  reward: 0
  closed: true
- id: 6
  gameMode: 1
  nextMissionId: 0
  mapId: 68
  minLevel: 1
  maxLevel: 0
  preMissionId: 0
  waitingTime: 0
  reward: 0
  closed: true
- id: 7
  gameMode: 1
  nextMissionId: 0
  mapId: 1
  minLevel: 1
  maxLevel: 0
  preMissionId: 0
  waitingTime: 0
  reward: 0
  closed: true
- id: 8
  gameMode: 1
  nextMissionId: 0
  mapId: 9
  minLevel: 1
  maxLevel: 0
  preMissionId: 0
  waitingTime: 0
  reward: 0
  closed: true
- id: 9
  gameMode: 1
  nextMissionId: 0
  mapId: 102
  minLevel: 1
  maxLevel: 0
  preMissionId: 0
  waitingTime: 0
  reward: 0
  closed: true
- id: 10
  gameMode: 1
  nextMissionId: 0
  mapId: 50
  minLevel: 1
  maxLevel: 0
  preMissionId: 0
  waitingTime: 5
  reward: 0
  closed: true
- id: 11
  gameMode: 1
  nextMissionId: 0
  mapId: 101
  minLevel: 1
  maxLevel: 0
  preMissionId: 0
  waitingTime: 0
  reward: 0
  closed: true
- id: 12
  gameMode: 1
  nextMissionId: 0
  mapId: 102
  minLevel: 0
  maxLevel: 0
  preMissionId: 0
  waitingTime: 0
  reward: 0
  closed: true
- id: 13
  gameMode: 1
  nextMissionId: 0
  mapId: 102
  minLevel: 0
  maxLevel: 0
  preMissionId: 0
  waitingTime: 0
  reward: 0
  closed: true
- id: 14
  gameMode: 1
  nextMissionId: 0
  mapId: 102
  minLevel: 0
  maxLevel: 0
  preMissionId: 0
  waitingTime: 0
  reward: 0
  closed: true
- id: 15
  gameMode: 1
  nextMissionId: 0
  mapId: 102
  minLevel: 0
  maxLevel: 0
  preMissionId: 0
  waitingTime: 0
  reward: 0
  closed: true
- id: 16
  gameMode: 1
  nextMissionId: 0
  mapId: 2
  minLevel: 1
  maxLevel: 0
  preMissionId: 0
  waitingTime: 5
  reward: 0
  closed: true
- id: 17
  gameMode: 1
  nextMissionId: 0
  mapId: 72
  minLevel: 1
  maxLevel: 0
  preMissionId: 0
  waitingTime: 5
  reward: 0
  closed: true
- id: 18
  gameMode: 1
  nextMissionId: 0
  mapId: 74
  minLevel: 1
  maxLevel: 0
  preMissionId: 0
  waitingTime: 0
  reward: 0
  closed: true
- id: 19
  gameMode: 1
  nextMissionId: 0
  mapId: 75
  minLevel: 0
  maxLevel: 0
  preMissionId: 0
  waitingTime: 0
  reward: 0
  closed: true
- id: 20
  gameMode: 1
  nextMissionId: 0
  mapId: 35
  minLevel: 1
  maxLevel: 0
  preMissionId: 0
  waitingTime: 0
  reward: 0
  closed: true
- id: 21
  gameMode: 1
  nextMissionId: 0
  mapId: 1
  minLevel: 0
  maxLevel: 0
  preMissionId: 0
  waitingTime: 0
  reward: 0
  closed: true
- id: 22
  gameMode: 1
  nextMissionId: 0
  mapId: 76
  minLevel: 0
  maxLevel: 0
  preMissionId: 0
  waitingTime: 0
  reward: 0
  closed: true
- id: 23
  gameMode: 1
  nextMissionId: 0
  mapId: 75
  minLevel: 0
  maxLevel: 0
  preMissionId: 0
  waitingTime: 0
  reward: 0
  closed: true
- id: 24
  gameMode: 1
  nextMissionId: 0
  mapId: 20004
  minLevel: 1
  maxLevel: 0
  preMissionId: 0
  waitingTime: 5
  reward: 0
  closed: true
- id: 25
  gameMode: 1
  nextMissionId: 0
  mapId: 0
  minLevel: 0
  maxLevel: 0
  preMissionId: 0
  waitingTime: 0
  reward: 0
  closed: true
- id: 26
  gameMode: 1
  nextMissionId: 0
  mapId: 0
  minLevel: 0
  maxLevel: 0
  preMissionId: 0
  waitingTime: 0
  reward: 0
  closed: true
- id: 27
  gameMode: 1
  nextMissionId: 0
  mapId: 0
  minLevel: 0
  maxLevel: 0
  preMissionId: 0
  waitingTime: 0
  reward: 0
  closed: true
- id: 28
  gameMode: 1
  nextMissionId: 0
  mapId: 0
  minLevel: 0
  maxLevel: 0
  preMissionId: 0
  waitingTime: 0
  reward: 0
  closed: true
- id: 29
  gameMode: 1
  nextMissionId: 0
  mapId: 0
  minLevel: 0
  maxLevel: 0
  preMissionId: 0
  waitingTime: 0
  reward: 0
  closed: true
- id: 30
  gameMode: 1
  nextMissionId: 0
  mapId: 0
  minLevel: 0
  maxLevel: 0
  preMissionId: 0
  waitingTime: 0
  reward: 0
  closed: true
- id: 31
  gameMode: 1
  nextMissionId: 32
  mapId: 67
  minLevel: 1
  maxLevel: 0
  preMissionId: 0
  waitingTime: 5
  reward: 200
  closed: false
- id: 32
  gameMode: 1
  nextMissionId: 33
  mapId: 67
  minLevel: 1
  maxLevel: 0
  preMissionId: 31
  waitingTime: 5
  reward: 200
  closed: false
- id: 33
  gameMode: 1
  nextMissionId: 46
  mapId: 67
  minLevel: 1
  maxLevel: 0
  preMissionId: 32
  waitingTime: 5
  reward: 200
  closed: false
- id: 34
  gameMode: 1
  nextMissionId: 49
  mapId: 67
  minLevel: 1
  maxLevel: 0
  preMissionId: 35
  waitingTime: 5
  reward: 200
  closed: false
- id: 35
  gameMode: 1
  nextMissionId: 34
  mapId: 67
  minLevel: 1
  maxLevel: 0
  preMissionId: 46
  waitingTime: 5
  reward: 200
  closed: false
- id: 39
  gameMode: 1
  nextMissionId: 0
  mapId: 35
  minLevel: 1
  maxLevel: 0
  preMissionId: 0
  waitingTime: 5
  reward: 0
  closed: true
- id: 40
  gameMode: 1
  nextMissionId: 0
  mapId: 0
  minLevel: 0
  maxLevel: 0
  preMissionId: 0
  waitingTime: 0
  reward: 0
  closed: true
- id: 41
  gameMode: 2
  nextMissionId: 42
  mapId: 67
  minLevel: 1
  maxLevel: 0
  preMissionId: 0
  waitingTime: 5
  reward: 200
  closed: false
- id: 42
  gameMode: 2
  nextMissionId: 43
  mapId: 67
  minLevel: 1
  maxLevel: 0
  preMissionId: 41
  waitingTime: 5
  reward: 200
  closed: false
- id: 43
  gameMode: 2
  nextMissionId: 46
  mapId: 67
  minLevel: 1
  maxLevel: 0
  preMissionId: 42
  waitingTime: 5
  reward: 200
  closed: false
- id: 44
  gameMode: 2
  nextMissionId: 45
  mapId: 67
  minLevel: 1
  maxLevel: 0
  preMissionId: 34
  waitingTime: 5
  reward: 200
  closed: false
- id: 45
  gameMode: 2
  nextMissionId: 0
  mapId: 67
  minLevel: 1
  maxLevel: 0
  preMissionId: 44
  waitingTime: 5
  reward: 200
  closed: false
- id: 46
  gameMode: 1
  nextMissionId: 35
  mapId: 67
  minLevel: 1
  maxLevel: 0
  preMissionId: 33
  waitingTime: 5
  reward: 200
  closed: false
- id: 49
  gameMode: 1
  nextMissionId: 50
  mapId: 67
  minLevel: 1
  maxLevel: 0
  preMissionId: 34
  waitingTime: 5
  reward: 200
  closed: false
- id: 50
  gameMode: 1
  nextMissionId: 51
  mapId: 67
  minLevel: 1
  maxLevel: 0
  preMissionId: 49
  waitingTime: 5
  reward: 200
  closed: false
- id: 51
  gameMode: 1
  nextMissionId: 0
  mapId: 67
  minLevel: 1
  maxLevel: 0
  preMissionId: 50
  waitingTime: 5
  reward: 200
  closed: false
- id: 100
  gameMode: 1
  nextMissionId: 0
  mapId: 0
  minLevel: 0
  maxLevel: 0
  preMissionId: 0
  waitingTime: 0
  reward: 0
  closed: false
- id: 101
  gameMode: 1
  nextMissionId: 0
  mapId: 0
  minLevel: 0
  maxLevel: 0
  preMissionId: 0
  waitingTime: 0
  reward: 0
  closed: false
