missions:
- id: 1
  nextMissionId: 0
  mapId: 65
  minLevel: 1
  maxLevel: 0
  preMissionId: 0
  waitingTime: 0
  reward: 0
  closed: true
- id: 2
  nextMissionId: 0
  mapId: 65
  minLevel: 1
  maxLevel: 0
  preMissionId: 0
  waitingTime: 0
  reward: 0
  closed: true
- id: 3
  nextMissionId: 0
  mapId: 67
  minLevel: 1
  maxLevel: 0
  preMissionId: 0
  waitingTime: 0
  reward: 0
  closed: true
- id: 4
  nextMissionId: 0
  mapId: 66
  minLevel: 1
  maxLevel: 0
  preMissionId: 0
  waitingTime: 0
  reward: 0
  closed: true
- id: 5
  nextMissionId: 0
  mapId: 66
  minLevel: 1
  maxLevel: 0
  preMissionId: 0
  waitingTime: 0
  reward: 0
  closed: true
- id: 6
  nextMissionId: 0
  mapId: 68
  minLevel: 1
  maxLevel: 0
  preMissionId: 0
  waitingTime: 0
  reward: 0
  closed: true
- id: 7
  nextMissionId: 0
  mapId: 1
  minLevel: 1
  maxLevel: 0
  preMissionId: 0
  waitingTime: 0
  reward: 0
  closed: true
- id: 8
  nextMissionId: 0
  mapId: 9
  minLevel: 1
  maxLevel: 0
  preMissionId: 0
  waitingTime: 0
  reward: 0
  closed: true
- id: 9
  nextMissionId: 0
  mapId: 102
  minLevel: 1
  maxLevel: 0
  preMissionId: 0
  waitingTime: 0
  reward: 0
  closed: true
- id: 10
  nextMissionId: 0
  mapId: 50
  minLevel: 1
  maxLevel: 0
  preMissionId: 0
  waitingTime: 5
  reward: 0
  closed: true
- id: 11
  nextMissionId: 0
  mapId: 101
  minLevel: 1
  maxLevel: 0
  preMissionId: 0
  waitingTime: 0
  reward: 0
  closed: true
- id: 12
  nextMissionId: 0
  mapId: 102
  minLevel: 0
  maxLevel: 0
  preMissionId: 0
  waitingTime: 0
  reward: 0
  closed: true
- id: 13
  nextMissionId: 0
  mapId: 102
  minLevel: 0
  maxLevel: 0
  preMissionId: 0
  waitingTime: 0
  reward: 0
  closed: true
- id: 14
  nextMissionId: 0
  mapId: 102
  minLevel: 0
  maxLevel: 0
  preMissionId: 0
  waitingTime: 0
  reward: 0
  closed: true
- id: 15
  nextMissionId: 0
  mapId: 102
  minLevel: 0
  maxLevel: 0
  preMissionId: 0
  waitingTime: 0
  reward: 0
  closed: true
- id: 16
  nextMissionId: 0
  mapId: 2
  minLevel: 1
  maxLevel: 0
  preMissionId: 0
  waitingTime: 5
  reward: 0
  closed: true
- id: 17
  nextMissionId: 0
  mapId: 72
  minLevel: 1
  maxLevel: 0
  preMissionId: 0
  waitingTime: 5
  reward: 0
  closed: true
- id: 18
  nextMissionId: 0
  mapId: 74
  minLevel: 1
  maxLevel: 0
  preMissionId: 0
  waitingTime: 0
  reward: 0
  closed: true
- id: 19
  nextMissionId: 0
  mapId: 75
  minLevel: 0
  maxLevel: 0
  preMissionId: 0
  waitingTime: 0
  reward: 0
  closed: true
- id: 20
  nextMissionId: 0
  mapId: 35
  minLevel: 1
  maxLevel: 0
  preMissionId: 0
  waitingTime: 0
  reward: 0
  closed: true
- id: 21
  nextMissionId: 0
  mapId: 1
  minLevel: 0
  maxLevel: 0
  preMissionId: 0
  waitingTime: 0
  reward: 0
  closed: true
- id: 22
  nextMissionId: 0
  mapId: 76
  minLevel: 0
  maxLevel: 0
  preMissionId: 0
  waitingTime: 0
  reward: 0
  closed: true
- id: 23
  nextMissionId: 0
  mapId: 75
  minLevel: 0
  maxLevel: 0
  preMissionId: 0
  waitingTime: 0
  reward: 0
  closed: true
- id: 24
  nextMissionId: 0
  mapId: 20004
  minLevel: 1
  maxLevel: 0
  preMissionId: 0
  waitingTime: 5
  reward: 0
  closed: true
- id: 25
  nextMissionId: 0
  mapId: 0
  minLevel: 0
  maxLevel: 0
  preMissionId: 0
  waitingTime: 0
  reward: 0
  closed: true
- id: 26
  nextMissionId: 0
  mapId: 0
  minLevel: 0
  maxLevel: 0
  preMissionId: 0
  waitingTime: 0
  reward: 0
  closed: true
- id: 27
  nextMissionId: 0
  mapId: 0
  minLevel: 0
  maxLevel: 0
  preMissionId: 0
  waitingTime: 0
  reward: 0
  closed: true
- id: 28
  nextMissionId: 0
  mapId: 0
  minLevel: 0
  maxLevel: 0
  preMissionId: 0
  waitingTime: 0
  reward: 0
  closed: true
- id: 29
  nextMissionId: 0
  mapId: 0
  minLevel: 0
  maxLevel: 0
  preMissionId: 0
  waitingTime: 0
  reward: 0
  closed: true
- id: 30
  nextMissionId: 0
  mapId: 0
  minLevel: 0
  maxLevel: 0
  preMissionId: 0
  waitingTime: 0
  reward: 0
  closed: true
- id: 31
  nextMissionId: 32
  mapId: 67
  minLevel: 1
  maxLevel: 0
  preMissionId: 0
  waitingTime: 5
  reward: 200
  closed: false
- id: 32
  nextMissionId: 33
  mapId: 67
  minLevel: 1
  maxLevel: 0
  preMissionId: 31
  waitingTime: 5
  reward: 200
  closed: false
- id: 33
  nextMissionId: 46
  mapId: 67
  minLevel: 1
  maxLevel: 0
  preMissionId: 32
  waitingTime: 5
  reward: 200
  closed: false
- id: 34
  nextMissionId: 49
  mapId: 67
  minLevel: 1
  maxLevel: 0
  preMissionId: 35
  waitingTime: 5
  reward: 200
  closed: false
- id: 35
  nextMissionId: 34
  mapId: 67
  minLevel: 1
  maxLevel: 0
  preMissionId: 46
  waitingTime: 5
  reward: 200
  closed: false
- id: 39
  nextMissionId: 0
  mapId: 35
  minLevel: 1
  maxLevel: 0
  preMissionId: 0
  waitingTime: 5
  reward: 0
  closed: true
- id: 40
  nextMissionId: 0
  mapId: 0
  minLevel: 0
  maxLevel: 0
  preMissionId: 0
  waitingTime: 0
  reward: 0
  closed: true
- id: 41
  nextMissionId: 42
  mapId: 67
  minLevel: 1
  maxLevel: 0
  preMissionId: 0
  waitingTime: 5
  reward: 200
  closed: false
- id: 42
  nextMissionId: 43
  mapId: 67
  minLevel: 1
  maxLevel: 0
  preMissionId: 41
  waitingTime: 5
  reward: 200
  closed: false
- id: 43
  nextMissionId: 46
  mapId: 67
  minLevel: 1
  maxLevel: 0
  preMissionId: 42
  waitingTime: 5
  reward: 200
  closed: false
- id: 44
  nextMissionId: 45
  mapId: 67
  minLevel: 1
  maxLevel: 0
  preMissionId: 34
  waitingTime: 5
  reward: 200
  closed: false
- id: 45
  nextMissionId: 0
  mapId: 67
  minLevel: 1
  maxLevel: 0
  preMissionId: 44
  waitingTime: 5
  reward: 200
  closed: false
- id: 46
  nextMissionId: 35
  mapId: 67
  minLevel: 1
  maxLevel: 0
  preMissionId: 33
  waitingTime: 5
  reward: 200
  closed: false
- id: 49
  nextMissionId: 50
  mapId: 67
  minLevel: 1
  maxLevel: 0
  preMissionId: 34
  waitingTime: 5
  reward: 200
  closed: false
- id: 50
  nextMissionId: 51
  mapId: 67
  minLevel: 1
  maxLevel: 0
  preMissionId: 49
  waitingTime: 5
  reward: 200
  closed: false
- id: 51
  nextMissionId: 0
  mapId: 67
  minLevel: 1
  maxLevel: 0
  preMissionId: 50
  waitingTime: 5
  reward: 200
  closed: false
- id: 100
  nextMissionId: 0
  mapId: 0
  minLevel: 0
  maxLevel: 0
  preMissionId: 0
  waitingTime: 0
  reward: 0
  closed: false
- id: 101
  nextMissionId: 0
  mapId: 0
  minLevel: 0
  maxLevel: 0
  preMissionId: 0
  waitingTime: 0
  reward: 0
  closed: false
